# -*- coding: utf-8 -*-
"""Sentiment Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pQoeGsX7X0nOszz2Z_Fs1_MO3vmwdYE
"""

import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')

df = pd.read_csv("/content/data.csv")
df.head()

df = df[['Review text', 'Ratings']]

df = df[df['Ratings'] != 3]

df['sentiment'] = df['Ratings'].apply(lambda x: 1 if x >= 4 else 0)

df['sentiment'].value_counts()

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['clean_review'] = df['Review text'].apply(clean_text)

df[['Review text', 'clean_review']].head()

X = df['clean_review']
y = df['sentiment']

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("F1 Score:", f1_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

def predict_sentiment(review):
    review_clean = clean_text(review)
    review_vec = tfidf.transform([review_clean])
    pred = model.predict(review_vec)[0]
    return "Positive 😊" if pred == 1 else "Negative 😞"

# Example
predict_sentiment("Very bad quality, shuttle broke in one match")

import pickle

pickle.dump(model, open("sentiment_model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

